language: python
python:
#  - "3.3"
  - "2.7"
#  - "2.6"
# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors
# command to run tests, e.g. python setup.py test
#script:  nosetests
#script: python tests/test_all_of_the_units.py